replicaCount: 2

image:
  repository: jkalume/kari-git-images
  pullPolicy: IfNotPresent
  tag: 20230130.1

service:
  type: LoadBalancer
  port: 4000
  targetPort: 4000
  protocol: TCP
  name: node-app-service

resources: {}
limits:
    cpu: 100m
    memory: 256Mi
requests:
    cpu: 100m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80